// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package easyjsonprocess

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB23cf6c4DecodeGoRedisEasyjsonprocess(in *jlexer.Lexer, out *CancelBuyReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userId":
			out.UserId = string(in.String())
		case "orderNum":
			out.OrderNum = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB23cf6c4EncodeGoRedisEasyjsonprocess(out *jwriter.Writer, in CancelBuyReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userId\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserId))
	}
	{
		const prefix string = ",\"orderNum\":"
		out.RawString(prefix)
		out.String(string(in.OrderNum))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CancelBuyReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB23cf6c4EncodeGoRedisEasyjsonprocess(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CancelBuyReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB23cf6c4EncodeGoRedisEasyjsonprocess(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CancelBuyReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB23cf6c4DecodeGoRedisEasyjsonprocess(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CancelBuyReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB23cf6c4DecodeGoRedisEasyjsonprocess(l, v)
}
func easyjsonB23cf6c4DecodeGoRedisEasyjsonprocess1(in *jlexer.Lexer, out *BuyReq) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userId":
			out.UserId = string(in.String())
		case "productId":
			out.ProductId = string(in.String())
		case "purchaseNum":
			out.PurchaseNum = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB23cf6c4EncodeGoRedisEasyjsonprocess1(out *jwriter.Writer, in BuyReq) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"userId\":"
		out.RawString(prefix[1:])
		out.String(string(in.UserId))
	}
	{
		const prefix string = ",\"productId\":"
		out.RawString(prefix)
		out.String(string(in.ProductId))
	}
	{
		const prefix string = ",\"purchaseNum\":"
		out.RawString(prefix)
		out.Int(int(in.PurchaseNum))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BuyReq) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB23cf6c4EncodeGoRedisEasyjsonprocess1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BuyReq) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB23cf6c4EncodeGoRedisEasyjsonprocess1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BuyReq) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB23cf6c4DecodeGoRedisEasyjsonprocess1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BuyReq) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB23cf6c4DecodeGoRedisEasyjsonprocess1(l, v)
}
